services:
  api-gateway:
    build: ./api-gateway/
    ports:
      - 8080:8080
    depends_on:
      - service-registry
    environment:
      - EUREKA_INSTANCE_HOSTNAME=host.docker.internal
      - EUREKA_URL=http://host.docker.internal:8761/eureka/
  authuser:
    build: ./authuser
    ports:
      - 8087:8087
    depends_on:
      - service-registry
      - postgres
    environment:
      - EUREKA_INSTANCE_HOSTNAME=host.docker.internal
      - EUREKA_URL=http://host.docker.internal:8761/eureka/
      - API_COURSE_BASEURL=http://host.docker.internal:8082
      - API_COURSE_ENDPOINT=courses
      - API_COURSE_ENDPOINT_PROPAG_DEL=/courses/users/{userId}
      - PSQL_PASS=pass
      - PSQL_USER=postgres
      - PSQL_HOST=host.docker.internal
  course:
    build: ./course
    ports:
      - 8082:8082
    depends_on:
      - service-registry
      - postgres
    environment:
      - EUREKA_INSTANCE_HOSTNAME=host.docker.internal
      - EUREKA_URL=http://host.docker.internal:8761/eureka/
      - API_USER_BASEURL=http://host.docker.internal:8087
      - API_USER_ENDPOINT=users
      - API_USER_ENDPOINT_PROPAG_SUBS=users/{userId}/courses/subscription
      - PSQL_PASS=pass
      - PSQL_USER=postgres
      - PSQL_HOST=host.docker.internal
      - API_USER_ENDPOINT_PROPAG_DEL=/users/courses/{courseId}
  notification:
    build: ./notification
    ports:
      - 8085:8085
    depends_on:
      - service-registry
    environment:
      - EUREKA_INSTANCE_HOSTNAME=host.docker.internal
      - EUREKA_URL=http://host.docker.internal:8761/eureka/
  service-registry:
    build: ./service-registry/
    ports:
      - 8761:8761
  config-server:
    build: ./config-server/
    ports:
      - 8888:8888
    environment:
      - EUREKA_INSTANCE_HOSTNAME=host.docker.internal
      - EUREKA_URL=http://host.docker.internal:8761/eureka/
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
#      - type: volume
      - dbdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  dbdata:
    driver: local
  rabbitmq_data:
    driver: local