x-global-env: &env
  EUREKA_INSTANCE_HOSTNAME: host.docker.internal
#  EUREKA_URL=http://host.docker.internal:8761/eureka/
  EUREKA_URL: http://serviceregistry:ead123@host.docker.internal:8761/eureka/
x-global-env-config-server: &env-config-server
  APP_CONFIG_SERVER_USERNAME: configserver
  APP_CONFIG_SERVER_PASSWORD: ead123
services:
  api-gateway:
    build: ./api-gateway/
    ports:
      - 8080:8080
    depends_on:
      - service-registry
      - config-server
    environment:
      <<: *env
      <<: *env-config-server
  authuser:
    build: ./authuser
    ports:
      - 8087:8087
    depends_on:
      - service-registry
      - config-server
      - postgres
    environment:
      <<: *env
      <<: *env-config-server
      HOST_DOCKER: host.docker.internal
      API_COURSE_BASEURL: http://host.docker.internal:8082
      API_COURSE_ENDPOINT: courses
      API_COURSE_ENDPOINT_PROPAG_DEL: /courses/users/{userId}
      PSQL_PASS: pass
      PSQL_USER: postgres
      PSQL_HOST: host.docker.internal
  course:
    build: ./course
    ports:
      - 8082:8082
    depends_on:
      - service-registry
      - config-server
      - postgres
    environment:
      <<: *env
      <<: *env-config-server
      HOST_DOCKER: host.docker.internal
      API_USER_BASEURL: http://host.docker.internal:8087
      API_USER_ENDPOINT: users
      API_USER_ENDPOINT_PROPAG_SUBS: users/{userId}/courses/subscription
      PSQL_PASS: pass
      PSQL_USER: postgres
      PSQL_HOST: host.docker.internal
      API_USER_ENDPOINT_PROPAG_DEL: /users/courses/{courseId}
  notification:
    build: ./notification
    ports:
      - 8084:8084
    depends_on:
      - service-registry
      - config-server
      - postgres
    environment:
      <<: *env
      <<: *env-config-server
      HOST_DOCKER: host.docker.internal
      PSQL_PASS: pass
      PSQL_USER: postgres
      PSQL_HOST: host.docker.internal
  service-registry:
    build: ./service-registry/
    ports:
      - 8761:8761
    environment:
      <<: *env
      APP_SERVICE_REGISTRY_USERNAME: serviceregistry
      APP_SERVICE_REGISTRY_PASSWORD: ead123
  config-server:
    build: ./config-server/
    ports:
      - 8888:8888
    depends_on:
      - service-registry
    environment:
      <<: *env
      <<: *env-config-server
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
#      - type: volume
      - dbdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  dbdata:
    driver: local
  rabbitmq_data:
    driver: local
