server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser
          uri: lb://authuser
          predicates:
            - Path=/ead-authuser/**
        - id: course
          uri: lb://course
          predicates:
            - Path=/ead-course/**
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
