spring:
  application:
    name: notification
  servlet:
    context-path: '/ead-notification'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}