server:
  port: 8082
  servlet:
    context-path: '/ead-course'

spring:
  application:
    name: course
  datasource:
    password: ${PSQL_PASS}
    username: ${PSQL_USER}
    url: jdbc:postgresql://${PSQL_HOST}:5432/ead-course-v2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # not needed in hibernate 6+
        show_sql: true
  rabbitmq:
    port: 5672

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace # shows preparedStatement parameters

api:
  user:
    base-url: authuser
    endpoint: ${API_USER_ENDPOINT}
    endpoint-propagate-subscription: ${API_USER_ENDPOINT_PROPAG_SUBS}
    endpoint-propagate-deletion: ${API_USER_ENDPOINT_PROPAG_DEL}
  broker:
    exchange:
      userEvent: ead.userevent # exchange name
    queue:
      userEventQueue:
        name: ead.userevent.ms.course

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
