spring:
  application:
    name: course

  datasource:
    password: ${PSQL_PASS}
    username: ${PSQL_USER}
    url: jdbc:postgresql://localhost:5432/ead-course
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # not needed in hibernate 6+
        show_sql: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace # shows preparedStatement parameters
server:
  port: 8082

api:
  user:
    base-url: ${API_USER_BASEURL}
    endpoint: ${API_USER_ENDPOINT}
    endpoint-propagate-subscription: ${API_USER_ENDPOINT_PROPAG_SUBS}
